import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { insights } from "@/data/demoData";
import {
  DemoTag,
  MetricCard,
  Panel,
  PageHeader,
  StatusBadge,
} from "@/components/common/primitives";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_shell/insights")({
  head: () => ({
    meta: [
      { title: "AI Insights — HyperLoop AI" },
      {
        name: "description",
        content:
          "Observations, anomalies, predictions and optimization opportunities found in your storage.",
      },
      { property: "og:title", content: "AI Insights — HyperLoop AI" },
      {
        property: "og:description",
        content: "The AI decision center for your cloud storage.",
      },
    ],
  }),
  component: InsightsPage,
});

const CATEGORIES = ["All", "Opportunity", "Anomaly", "Prediction", "Observation"] as const;

function InsightsPage() {
  const [filter, setFilter] = useState<(typeof CATEGORIES)[number]>("All");
  const [open, setOpen] = useState<string | null>(insights[0].id);

  const list = insights.filter((i) => filter === "All" || i.category === filter);
  const totalImpact = insights.reduce((s, i) => s + i.impactGb, 0);

  return (
    <div>
      <PageHeader
        title="AI insights"
        description="What HyperLoop observed, why it matters, and what it suggests doing next."
        actions={<DemoTag />}
      />

      <div className="grid gap-4 md:grid-cols-3">
        <MetricCard
          label="Open insights"
          value={String(insights.length)}
          hint="Generated by the latest analysis sweep"
        />
        <MetricCard
          label="Potential impact"
          value={totalImpact.toFixed(1)}
          unit="GB"
          hint="Combined recoverable storage"
          tone="success"
        />
        <MetricCard
          label="High confidence"
          value={String(insights.filter((i) => i.confidence === "High").length)}
          hint="Supported by strong evidence"
          tone="violet"
        />
      </div>

      <div className="mt-5 flex flex-wrap gap-2">
        {CATEGORIES.map((c) => (
          <button
            key={c}
            onClick={() => setFilter(c)}
            className={cn(
              "rounded-full border px-3 py-1.5 text-xs transition-colors",
              filter === c
                ? "border-primary/40 bg-primary/12 text-primary"
                : "border-border text-muted-foreground hover:text-foreground",
            )}
          >
            {c}
          </button>
        ))}
      </div>

      <div className="mt-4 space-y-3">
        {list.map((i) => {
          const expanded = open === i.id;
          return (
            <Panel key={i.id} className="p-0">
              <button
                onClick={() => setOpen(expanded ? null : i.id)}
                className="flex w-full items-start justify-between gap-4 p-5 text-left"
              >
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-sm font-semibold">{i.title}</h3>
                    <StatusBadge
                      tone={
                        i.category === "Anomaly"
                          ? "warning"
                          : i.category === "Prediction"
                            ? "violet"
                            : i.category === "Opportunity"
                              ? "success"
                              : "info"
                      }
                    >
                      {i.category}
                    </StatusBadge>
                  </div>
                  <p className="mt-1.5 text-xs text-muted-foreground">{i.description}</p>
                </div>
                <ChevronDown
                  className={cn(
                    "mt-1 size-4 shrink-0 text-muted-foreground transition-transform",
                    expanded && "rotate-180",
                  )}
                />
              </button>

              {expanded && (
                <div className="grid gap-5 border-t border-border p-5 lg:grid-cols-3">
                  <div className="lg:col-span-2 space-y-4">
                    <div>
                      <p className="text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">
                        Reason
                      </p>
                      <p className="mt-1 text-sm">{i.reason}</p>
                    </div>
                    <div>
                      <p className="text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">
                        Evidence
                      </p>
                      <ul className="mt-2 flex flex-wrap gap-2">
                        {i.evidence.map((e) => (
                          <li
                            key={e}
                            className="rounded-md border border-border bg-muted/40 px-2.5 py-1 text-xs"
                          >
                            {e}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  <div className="space-y-3 rounded-xl border border-border bg-muted/20 p-4">
                    <div className="flex justify-between text-xs">
                      <span className="text-muted-foreground">Potential impact</span>
                      <span className="font-semibold text-accent">
                        {i.impactGb.toFixed(1)} GB
                      </span>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-muted-foreground">Confidence</span>
                      <StatusBadge tone={i.confidence === "High" ? "success" : "info"}>
                        {i.confidence}
                      </StatusBadge>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-muted-foreground">Risk</span>
                      <StatusBadge
                        tone={
                          i.risk === "High" ? "danger" : i.risk === "Medium" ? "warning" : "success"
                        }
                      >
                        {i.risk}
                      </StatusBadge>
                    </div>
                    <Link
                      to={i.category === "Prediction" ? "/simulator" : "/recommendations"}
                      className="mt-2 inline-flex w-full items-center justify-center rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground transition-opacity hover:opacity-90"
                    >
                      {i.action}
                    </Link>
                  </div>
                </div>
              )}
            </Panel>
          );
        })}
      </div>
    </div>
  );
}
