/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAgentsRouteImport } from './routes/_shell.agents'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellChatRouteImport } from './routes/_shell.chat'
import { Route as ShellCloudsRouteImport } from './routes/_shell.clouds'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFilesRouteImport } from './routes/_shell.files'
import { Route as ShellForecastRouteImport } from './routes/_shell.forecast'
import { Route as ShellInsightsRouteImport } from './routes/_shell.insights'
import { Route as ShellMigrationsRouteImport } from './routes/_shell.migrations'
import { Route as ShellMonitoringRouteImport } from './routes/_shell.monitoring'
import { Route as ShellRecommendationsRouteImport } from './routes/_shell.recommendations'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSimulatorRouteImport } from './routes/_shell.simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCloudsRoute = ShellCloudsRouteImport.update({
  id: '/clouds',
  path: '/clouds',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFilesRoute = ShellFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ShellRoute,
} as any)
const ShellForecastRoute = ShellForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInsightsRoute = ShellInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMigrationsRoute = ShellMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitoringRoute = ShellMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecommendationsRoute = ShellRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSimulatorRoute = ShellSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof ShellAgentsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/chat': typeof ShellChatRoute
  '/clouds': typeof ShellCloudsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/files': typeof ShellFilesRoute
  '/forecast': typeof ShellForecastRoute
  '/insights': typeof ShellInsightsRoute
  '/migrations': typeof ShellMigrationsRoute
  '/monitoring': typeof ShellMonitoringRoute
  '/recommendations': typeof ShellRecommendationsRoute
  '/settings': typeof ShellSettingsRoute
  '/simulator': typeof ShellSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof ShellAgentsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/chat': typeof ShellChatRoute
  '/clouds': typeof ShellCloudsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/files': typeof ShellFilesRoute
  '/forecast': typeof ShellForecastRoute
  '/insights': typeof ShellInsightsRoute
  '/migrations': typeof ShellMigrationsRoute
  '/monitoring': typeof ShellMonitoringRoute
  '/recommendations': typeof ShellRecommendationsRoute
  '/settings': typeof ShellSettingsRoute
  '/simulator': typeof ShellSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/agents': typeof ShellAgentsRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/clouds': typeof ShellCloudsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/files': typeof ShellFilesRoute
  '/_shell/forecast': typeof ShellForecastRoute
  '/_shell/insights': typeof ShellInsightsRoute
  '/_shell/migrations': typeof ShellMigrationsRoute
  '/_shell/monitoring': typeof ShellMonitoringRoute
  '/_shell/recommendations': typeof ShellRecommendationsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/simulator': typeof ShellSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/chat'
    | '/clouds'
    | '/dashboard'
    | '/files'
    | '/forecast'
    | '/insights'
    | '/migrations'
    | '/monitoring'
    | '/recommendations'
    | '/settings'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/chat'
    | '/clouds'
    | '/dashboard'
    | '/files'
    | '/forecast'
    | '/insights'
    | '/migrations'
    | '/monitoring'
    | '/recommendations'
    | '/settings'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/agents'
    | '/_shell/analytics'
    | '/_shell/chat'
    | '/_shell/clouds'
    | '/_shell/dashboard'
    | '/_shell/files'
    | '/_shell/forecast'
    | '/_shell/insights'
    | '/_shell/migrations'
    | '/_shell/monitoring'
    | '/_shell/recommendations'
    | '/_shell/settings'
    | '/_shell/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clouds': {
      id: '/_shell/clouds'
      path: '/clouds'
      fullPath: '/clouds'
      preLoaderRoute: typeof ShellCloudsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/files': {
      id: '/_shell/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof ShellFilesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/forecast': {
      id: '/_shell/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ShellForecastRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/insights': {
      id: '/_shell/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof ShellInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/migrations': {
      id: '/_shell/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof ShellMigrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitoring': {
      id: '/_shell/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof ShellMonitoringRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recommendations': {
      id: '/_shell/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof ShellRecommendationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/simulator': {
      id: '/_shell/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof ShellSimulatorRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAgentsRoute: typeof ShellAgentsRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellCloudsRoute: typeof ShellCloudsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFilesRoute: typeof ShellFilesRoute
  ShellForecastRoute: typeof ShellForecastRoute
  ShellInsightsRoute: typeof ShellInsightsRoute
  ShellMigrationsRoute: typeof ShellMigrationsRoute
  ShellMonitoringRoute: typeof ShellMonitoringRoute
  ShellRecommendationsRoute: typeof ShellRecommendationsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSimulatorRoute: typeof ShellSimulatorRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgentsRoute: ShellAgentsRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellChatRoute: ShellChatRoute,
  ShellCloudsRoute: ShellCloudsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFilesRoute: ShellFilesRoute,
  ShellForecastRoute: ShellForecastRoute,
  ShellInsightsRoute: ShellInsightsRoute,
  ShellMigrationsRoute: ShellMigrationsRoute,
  ShellMonitoringRoute: ShellMonitoringRoute,
  ShellRecommendationsRoute: ShellRecommendationsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSimulatorRoute: ShellSimulatorRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
